<a href="https://colab.research.google.com/github/JunaidLamture/CodeAlpha_ML/blob/main/Credit%20Score%20Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Credit Scoring Model
The Credit Scoring Model repository aims to build a predictive model for a bank, enabling data-driven lending decisions. This model utilizes the Logistic Regression classifier and decile methodology to formulate an effective lending strategy.

Problem Statement
Banks and financial institutions often face challenges in assessing the creditworthiness of loan applicants. Traditional methods of credit scoring rely on historical data and statistical analysis to determine a borrower's credit score. However, these methods may not always be effective in predicting the likelihood of loan repayment accurately.

Solution Overview
The Credit Scoring Model project offers a solution by leveraging machine learning techniques to predict the likelihood of loan repayment based on historical customer data. The project employs the Logistic Regression classifier, a popular algorithm for binary classification tasks, to build the predictive model. Additionally, it utilizes decile methodology to formulate business rules for accepting or rejecting new loan applications, thereby optimizing business profitability and market penetration.

Key Features
Utilizes Logistic Regression classifier for predictive modeling.
Implements decile methodology to formulate lending strategy.
Provides data-driven insights for making informed lending decisions.
Offers a comprehensive toolkit with training datasets and Python source code for hands-on learning and reuse.
Usage

# Importing libraries & functions

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression

# Importing dataset

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
dataset=pd.read_excel("/content/a_Dataset_CreditScoring.xlsx")

# Data preparation

In [4]:
# shows count of rows and columns
dataset.shape

(3000, 30)

In [5]:
#shows first few rows of the code
dataset.head()

,TARGET,ID,DerogCnt,CollectCnt,BanruptcyInd,InqCnt06,InqTimeLast,InqFinanceCnt24,TLTimeFirst,TLTimeLast,...,TL50UtilCnt,TLBalHCPct,TLSatPct,TLDel3060Cnt24,TLDel90Cnt24,TLDel60CntAll,TLOpenPct,TLBadDerogCnt,TLDel60Cnt24,TLOpen24Pct
0,1,582,3,3,0,4,0.0,5,117,27,...,3.0,0.9179,0.2083,2,3,7,0.2083,4,4,0.0000
1,1,662,15,9,0,3,1.0,3,14,14,...,1.0,0.8000,0.0000,0,0,0,1.0000,12,0,1.0000
2,1,805,0,0,0,1,5.0,1,354,7,...,5.0,0.3552,0.6538,0,1,1,0.7308,1,1,0.5263
3,1,1175,8,5,0,6,1.0,10,16,4,...,3.0,0.9127,0.2500,1,1,1,0.7500,7,1,1.3333
4,1,1373,3,1,0,9,0.0,8,130,52,...,1.0,1.2511,0.0000,0,1,4,0.1429,3,1,0.0000

In [6]:
#dropping customer ID column from the dataset
dataset=dataset.drop('ID',axis=1)
dataset.shape

(3000, 29)

In [7]:
# explore missing values
dataset.isna().sum()

TARGET               0
DerogCnt             0
CollectCnt           0
BanruptcyInd         0
InqCnt06             0
InqTimeLast        188
InqFinanceCnt24      0
TLTimeFirst          0
TLTimeLast           0
TLCnt03              0
TLCnt12              0
TLCnt24              0
TLCnt                3
TLSum               40
TLMaxSum            40
TLSatCnt             4
TLDel60Cnt           0
TLBadCnt24           0
TL75UtilCnt         99
TL50UtilCnt         99
TLBalHCPct          41
TLSatPct             4
TLDel3060Cnt24       0
TLDel90Cnt24         0
TLDel60CntAll        0
TLOpenPct            3
TLBadDerogCnt        0
TLDel60Cnt24         0
TLOpen24Pct          3
dtype: int64

In [8]:
# filling missing values with mean
dataset=dataset.fillna(dataset.mean())

In [9]:
# explore missing values post missing value fix
dataset.isna().sum()

TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

In [10]:
# # count of good loans (0) and bad loans (1)
# dataset['TARGET'].value_counts()

In [11]:
# # data summary across 0 & 1
# dataset.groupby('TARGET').mean()

## TRAIN TEST

In [12]:
y = dataset.iloc[:, 0].values
X = dataset.iloc[:, 1:29].values

training 2400 test 600

In [13]:
# splitting dataset into training and test (in ratio 80:20)

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=0,
                                                    stratify=y)

In [14]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Risk Model building

In [15]:
classifier =  LogisticRegression()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

# Model performance

In [16]:
print(confusion_matrix(y_test,y_pred))

[[487  13]
 [ 87  13]]

In [17]:
print(accuracy_score(y_test, y_pred))

0.8333333333333334

# Writing output file

In [18]:
predictions = classifier.predict_proba(X_test)
predictions

array([[0.61644691, 0.38355309],
       [0.9885656 , 0.0114344 ],
       [0.87069686, 0.12930314],
       ...,
       [0.94450568, 0.05549432],
       [0.46756903, 0.53243097],
       [0.94014209, 0.05985791]])

In [19]:
# writing model output file

df_prediction_prob = pd.DataFrame(predictions, columns = ['prob_0', 'prob_1'])
df_prediction_target = pd.DataFrame(classifier.predict(X_test), columns = ['predicted_TARGET'])
df_test_dataset = pd.DataFrame(y_test,columns= ['Actual Outcome'])

dfx=pd.concat([df_test_dataset, df_prediction_prob, df_prediction_target], axis=1)

dfx.to_csv("/content/drive/My Drive/Colab Notebooks/c1_Model_Prediction.xlsx", sep=',', encoding='UTF-8')

dfx.head()

   Actual Outcome    prob_0    prob_1  predicted_TARGET
0               1  0.616447  0.383553                 0
1               0  0.988566  0.011434                 0
2               1  0.870697  0.129303                 0
3               0  0.953963  0.046037                 0
4               1  0.726633  0.273367                 0